# Production settings
permalink: /:categories/:year/:month/:day/:title 
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "Gemfile"]
safe: true # use safe plugins

# Custom setting
production_url : http://krwenholz.github.com
source: .
destination: ./_site
lsi: false
highlighter: rouge # use syntax highlighting in code
future: true # do publish future posts
